// Объекты
defarr xm[15];
//___________________Выделение точек

sysv=sysvar(60);
fname="Measure.xyz";
m=GetCount(fname);

	i=0;
	iobj=0;
lab_1:
	i=i+1;
If (i<=sysv) {
if (GetObjType(GetObjNum(i))==1) {
rr=GetObjGeo(GetObjNum(i),xm);
str1=Str(xm[1]);
str2=Str(xm[2]);
str3=Str(xm[3]);
str_all=str1+"   "+str2+"   "+str3;
pos=0;
if (i==1) {pos=-1;}
st=PutStr(fname,str_all,pos);
//delete GetObjNum(i);
//color 0;
//point xm[1],xm[2],xm[3]+100;

}

goto lab_1;
}
exit;

